### ISSUE TITLE
_od not a layer in terrängkartan

### ISSUE THREAD

**Issue by eeenilsson** [klakar/LM_Open_QGIS_Styles#1]
LM_terrang_od.qml is incuded in the repo but does not correspond to any layer name in terrängkartan vector that was dwnloaded from lantmäteriet. Should it be renamed?

**Comment by klakar** [comment]
OD (Depth contour lines) has been deprecated from Lantmäteriet terrängkartan. There might still be old datasets out there that can use the style, so I suggest it remains for the time being.
